name: Trigger auto deployment for noport

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/noport-AutoDeployTrigger-48aa78ca-adee-42f7-80ce-b929cafd671c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NOPORT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NOPORT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NOPORT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: chrrossprivate.azurecr.io
          registryUsername: ${{ secrets.NOPORT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NOPORT_REGISTRY_PASSWORD }}
          containerAppName: noport
          resourceGroup: TestNoPort
          imageToBuild: chrrossprivate.azurecr.io/noport:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


